name: Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r vitivinicultura/requirements.txt

  unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pytest and pytest-cov
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r vitivinicultura/requirements.txt

    - name: Run unit tests
      run: |
        pytest --maxfail=5 --disable-warnings --cov=vitivinicultura vitivinicultura/tests/

  coverage:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r vitivinicultura/requirements.txt
        pip install coveralls

    - name: Run coverage and send to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pytest --cov=vitivinicultura --cov-report=xml
        coveralls


  # create-pull-request:
  #   runs-on: ubuntu-latest
  #   needs: unit-tests

  #   steps:
  #   - name: Fazer checkout do código
  #     uses: actions/checkout@v3

  #   - name: Criar Pull Request para develop
  #     uses: peter-evans/create-pull-request@v5
  #     with:
  #       branch: ${{ github.ref_name }}  # Usando ref_name para a branch atual
  #       base: develop  # A base será a branch 'develop'
  #       title: 'Merge das alterações da branch ${{ github.ref_name }} para develop'
  #       body: |
  #         Merge automatizado da branch ${{ github.ref_name }} para develop.


