name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - staging
      - master
  pull_request:
    branches:
      - develop
      - staging
      - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: List Repository Files
        run: ls -R


      - name: Check if requirements.txt exists
        run: |
          if [ -f requirements.txt ]; then
            echo "Found requirements.txt in root"
          elif [ -f FinanceInsight/requirements.txt ]; then
            echo "Found requirements.txt in FinanceInsight/"
          else
            echo "requirements.txt NOT FOUND!"
            exit 1
          fi
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r $GITHUB_WORKSPACE/FinanceInsight/requirements.txt
      
      # - name: Run Tests
      #   run: |
      #     pytest FinanceInsight/tests/

  build:
    name: Build and Package App
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: List Repository Files
        run: ls -R

      - name: Check if requirements.txt exists
        run: |
          if [ -f requirements.txt ]; then
            echo "Found requirements.txt in root"
          else
            echo "requirements.txt NOT FOUND!"
            exit 1
          fi
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r $GITHUB_WORKSPACE/requirements.txt
      
      - name: Package Application
        run: |
          tar -czf FinanceInsight.tar.gz FinanceInsight/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FinanceInsight-package
          path: FinanceInsight.tar.gz

  deploy:
    name: Deploy to Develop, Staging, or Production
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: FinanceInsight-package

      - name: Deploy to Develop
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Deploying to DEVELOPMENT environment..."
          # Adicione os comandos para rodar um ambiente de desenvolvimento

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "Deploying to STAGING environment..."
          # Adicione os comandos para staging

      - name: Deploy to Production
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Deploying to PRODUCTION environment..."
          # Adicione os comandos para produção
        
